apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
      matchLabels:
          app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: class/api:latest
          imagePullPolicy: Never
          ports:
            - containerPort:  8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/postgres

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
