version: '3'
    
services:
    react:
      build: .
      ports:
        - 3000:80
      environment:
        - REACT_APP_API=localhost:8000


networks:
  default:
    external:
      name: api_default