FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
ARG database_url
ENV DATABASE_URL=${database_url}
CMD ./start_with_migration.sh
